package com.revature.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * This class defines the Category domain
 * 
 * @author Pameni Gaelle & Roberto Rodriguez
 */

@Entity
@Table(name = "lighthouse.category")
public class Category {

	/**
	 * the category ID is auto generated by postgresSQL using sequence
	 */
	@Id
	@SequenceGenerator(name = "CAT_ID_SEQ", sequenceName = "cat_id_seq")
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "CAT_ID_SEQ")
	@Column(name = "cat_id")
	private int catID;

	/**
	 * name of the category
	 */
	@Column(name = "cat_name")
	private String category;

	public Category() {
		super();
	}

	public Category(int catID, String category) {
		super();
		this.catID = catID;
		this.category = category;
	}

	public int getCatID() {
		return catID;
	}

	public void setCatID(int catID) {
		this.catID = catID;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + catID;
		result = prime * result + ((category == null) ? 0 : category.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Category other = (Category) obj;
		if (catID != other.catID)
			return false;
		if (category == null) {
			if (other.category != null)
				return false;
		} else if (!category.equals(other.category))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Category [catID=" + catID + ", category=" + category + "]";
	}
}